<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="" host="DESKTOP-ITVU56T"><DocLocation><![CDATA[C:\Users\Teona Zaalishvili\Documents\Unified Functional Testing\test3]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[test3]]></DName>
<Res><![CDATA[Res21]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:47]]></Time>
<TimeTick>1642649147</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:47]]></Time>
<TimeTick>1642649147</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:47]]></Time>
<TimeTick>1642649147</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["teona"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:47]]></Time>
<TimeTick>1642649147</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["61e8d469998dca0640274d9eb31bdbd99b32a8d6"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:47]]></Time>
<TimeTick>1642649147</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:49]]></Time>
<TimeTick>1642649149</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="13" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:50]]></Time>
<TimeTick>1642649150</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:50]]></Time>
<TimeTick>1642649150</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="21" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="20" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2022 - 22:25:47" eTime="1/19/2022 - 22:25:52" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[test3 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T13" iterID="2" >
<Action rID="T14">
<AName><![CDATA[Action1]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:52]]></Time>
<TimeTick>1642649152</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:52]]></Time>
<TimeTick>1642649152</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="28" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:52]]></Time>
<TimeTick>1642649152</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Cherry"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:52]]></Time>
<TimeTick>1642649152</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:53]]></Time>
<TimeTick>1642649153</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:55]]></Time>
<TimeTick>1642649155</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:55]]></Time>
<TimeTick>1642649155</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:55]]></Time>
<TimeTick>1642649155</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="39" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="38" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2022 - 22:25:52" eTime="1/19/2022 - 22:25:55" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="25" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="24" status="Passed" >
<Disp><![CDATA[test3 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T23" iterID="3" >
<Action rID="T24">
<AName><![CDATA[Action1]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:55]]></Time>
<TimeTick>1642649155</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:55]]></Time>
<TimeTick>1642649155</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="47" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="46" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:56]]></Time>
<TimeTick>1642649156</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Perry"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:56]]></Time>
<TimeTick>1642649156</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="50" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:56]]></Time>
<TimeTick>1642649156</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="52" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:58]]></Time>
<TimeTick>1642649158</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="49" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:58]]></Time>
<TimeTick>1642649158</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[1/19/2022 - 22:25:58]]></Time>
<TimeTick>1642649158</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="57" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="56" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2022 - 22:25:55" eTime="1/19/2022 - 22:26:10" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="43" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="42" status="Passed" >
<Disp><![CDATA[test3 Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T33" iterID="4" >
<Action rID="T34">
<AName><![CDATA[Action1]]></AName>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:11]]></Time>
<TimeTick>1642649171</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:11]]></Time>
<TimeTick>1642649171</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="103" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="102" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:11]]></Time>
<TimeTick>1642649171</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Merry"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:11]]></Time>
<TimeTick>1642649171</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="106" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:11]]></Time>
<TimeTick>1642649171</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="108" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:13]]></Time>
<TimeTick>1642649173</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="110" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="105" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:13]]></Time>
<TimeTick>1642649173</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:13]]></Time>
<TimeTick>1642649173</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="113" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="112" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2022 - 22:26:10" eTime="1/19/2022 - 22:26:14" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="99" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="98" status="Passed" >
<Disp><![CDATA[test3 Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T43" iterID="5" >
<Action rID="T44">
<AName><![CDATA[Action1]]></AName>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:14]]></Time>
<TimeTick>1642649174</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:14]]></Time>
<TimeTick>1642649174</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="121" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="120" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:14]]></Time>
<TimeTick>1642649174</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Henry"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:14]]></Time>
<TimeTick>1642649174</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="124" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:14]]></Time>
<TimeTick>1642649174</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="126" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:16]]></Time>
<TimeTick>1642649176</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="128" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="123" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:16]]></Time>
<TimeTick>1642649176</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:16]]></Time>
<TimeTick>1642649176</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="131" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="130" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2022 - 22:26:14" eTime="1/19/2022 - 22:26:25" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="117" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="116" status="Passed" >
<Disp><![CDATA[test3 Iteration 5 (Row 5)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T53" iterID="6" >
<Action rID="T54">
<AName><![CDATA[Action1]]></AName>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:25]]></Time>
<TimeTick>1642649185</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:25]]></Time>
<TimeTick>1642649185</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="163" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="162" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:25]]></Time>
<TimeTick>1642649185</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Kerry"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:25]]></Time>
<TimeTick>1642649185</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="166" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:25]]></Time>
<TimeTick>1642649185</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="168" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:27]]></Time>
<TimeTick>1642649187</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="170" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="165" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:27]]></Time>
<TimeTick>1642649187</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:27]]></Time>
<TimeTick>1642649187</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="173" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="172" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2022 - 22:26:25" eTime="1/19/2022 - 22:26:28" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="159" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="158" status="Passed" >
<Disp><![CDATA[test3 Iteration 6 (Row 6)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T63" iterID="7" >
<Action rID="T64">
<AName><![CDATA[Action1]]></AName>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:28]]></Time>
<TimeTick>1642649188</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:28]]></Time>
<TimeTick>1642649188</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="181" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="180" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:28]]></Time>
<TimeTick>1642649188</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["Larry"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:28]]></Time>
<TimeTick>1642649188</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="184" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:28]]></Time>
<TimeTick>1642649188</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="186" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:30]]></Time>
<TimeTick>1642649190</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="188" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="183" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:30]]></Time>
<TimeTick>1642649190</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["File;Exit"]]></Details>
<Time><![CDATA[1/19/2022 - 22:26:30]]></Time>
<TimeTick>1642649190</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="191" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="190" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2022 - 22:26:28" eTime="1/19/2022 - 22:26:37" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="177" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>