<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Eastern Standard Time">
<General productName="HP Unified Functional Testing" productVer="11.50" os="" host="DESKTOP-ITVU56T"><DocLocation><![CDATA[C:\Users\Teona Zaalishvili\Documents\Unified Functional Testing\test2]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[test2]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Run "C:\Program Files (x86)\HP\Unified Functional Testing\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Login_process]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Login_process" started.]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<NodeArgs eType="Transaction" icon="6" nRep="12" nType="Start Transaction" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login_process]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Agent Name:.SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["teona"]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Agent Name:.SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Password:.SetSecureText]]></Obj>
<Details plainTxt="False" ><![CDATA["61e7755990d550ec579beb6d0d53d811f6af704b"]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Password:.SetSecureText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login_process]]></Obj>
<Details plainTxt="False" ><![CDATA[Transaction "Login_process" ended with "Pass" status (Total Duration: 0.2156 sec).]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<NodeArgs eType="Transaction" icon="10" nRep="20" nType="End Transaction" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login_process]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="14" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Date of Flight:.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["121223"]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:48]]></Time>
<TimeTick>1642559328</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="23" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Date of Flight:.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Fly From:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Frankfurt"]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:49]]></Time>
<TimeTick>1642559329</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="25" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly From:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Fly To:.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Los Angeles"]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:49]]></Time>
<TimeTick>1642559329</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="27" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Fly To:.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[FLIGHT.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/18/2022 - 21:28:50]]></Time>
<TimeTick>1642559330</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="29" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[FLIGHT.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Flights Table]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[1/18/2022 - 21:29:11]]></Time>
<TimeTick>1642559351</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/18/2022 - 21:29:11]]></Time>
<TimeTick>1642559351</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="103" status="Warning" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[OK]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "OK" object's parent "Flight Reservation" (class Window). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[1/18/2022 - 21:29:11]]></Time>
<TimeTick>1642559351</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Flight Reservation]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>regexpwndtitle = Flight Reservation<br>regexpwndclass = Afx:<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[1/18/2022 - 21:29:11]]></Time>
<TimeTick>1642559351</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="105" status="Warning" nType="Parent description" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="104" status="Failed" nType="Run Error" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[OK]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="102" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flights Table]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="22" status="Failed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Flight Reservation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;OK&quot; object's parent &quot;Flight Reservation&quot; (class Window). Verify that parent properties match an object currently displayed in your application.<BR>Line (15): &quot;Window(&quot;Flight Reservation&quot;).Dialog(&quot;Flights Table&quot;).WinButton(&quot;OK&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[1/18/2022 - 21:29:11]]></Time>
<TimeTick>1642559351</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="106" status="Failed" Source="Action1" SourceLine="14" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/18/2022 - 21:29:33]]></Time>
<TimeTick>1642559373</TimeTick>
<NodeArgs eType="General" icon="15" nRep="107" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/18/2022 - 21:28:48" eTime="1/18/2022 - 21:29:33" passed="1" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[test2 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="1/18/2022 - 21:28:47" eTime="1/18/2022 - 21:29:33" passed="1" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test test2 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>